name: First Workflow

on:
    push:
       branches:
         -main


jobs:
  example-job:
    runson: ubuntu:latest

    steps:
      - name: print a welcome message
        run: echo "Welcome to our first Github Actions Workflow!"

  
